clovia/urls.py
from django.urls import path

from . import views

app_name = 'clovia'
urlpatterns = [
    path("", views.home, name="home"),   
    path("<int:login_id>/", views.Meeting_RoomsView.as_view(), name="meeting_rooms"),
    path("<int:login_id>/<int:rooms_id>/", views.bookings, name="bookings"),    
    path("<int:login_id>/<int:rooms_id>/bookedslots/", views.slots, name="slots"),  
    path("<int:login_id>/meetings/", views.meetings, name="meetings"),
    path("<int:login_id>/bookings/", views.view_bookings, name="view_bookings"),    
    path('<int:login_id>/<int:booking_id>/edit/', views.edit_booking, name='edit_booking'),
    path('<int:booking_id>/view_participant/', views.view_participants, name='view_participants'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path("clovia/", include("clovia.urls")),
    path("polls/", include("polls.urls")),
    path("admin/", admin.site.urls),
]

urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path("demo/", include("demo.urls")),
    path("clovia/", include("clovia.urls")),
    path("polls/", include("polls.urls")),
    path("admin/", admin.site.urls),
]

clovia/models.py
from django.db import models

# Create your models here.
class Login(models.Model):
    username = models.EmailField(max_length=100,)
    password = models.CharField(max_length=15,)
    def __str__(self):
        return self.username
    
class Meeting_Rooms(models.Model):
    room=models.CharField(max_length=50)
    def __str__(self):
        return self.room
    
class Bookings(models.Model):
    user = models.ForeignKey(Login, on_delete=models.CASCADE)
    room_name = models.ForeignKey(Meeting_Rooms, on_delete=models.CASCADE)
    booking_date = models.DateField("Booking On")
    booking_time = models.TimeField("Booking At")
    end_time = models.TimeField("Ends At")
    participants = models.ManyToManyField(Login,related_name='bookings_participated')
    google_calendar_event_id = models.CharField(max_length=100, blank=True, null=True)
    def __str__(self):
        return f"{self.user.username} booked {self.room_name.room}  on {self.booking_date} at {self.booking_time} invited {self.participants}"

class Notification(models.Model):
    receiver = models.ForeignKey(Login, on_delete=models.CASCADE)
    is_read = models.BooleanField(default=False)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.message

   

clovia/forms.py
from django import forms
from .models import Login, Bookings
from django.core.exceptions import ValidationError

def validate_username(value):
    if not (value.endswith("@clovia.com") or value.endswith("@purplepanda.in")):
        raise ValidationError("Enter Organization Email Id")
        
class LoginForm(forms.ModelForm):
    username=forms.EmailField(validators=[validate_username])
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = Login
        fields = ('username', 'password')
        
class BookingForm(forms.ModelForm):
    class Meta:
        model=Bookings
        fields=('booking_date','booking_time','end_time','participants')
        widgets = {
            'booking_date': forms.DateInput(attrs={'type': 'date'}),            
            'booking_time': forms.TimeInput(attrs={'type': 'time'}),
            'end_time': forms.TimeInput(attrs={'type': 'time'}),
        }
        
                
class EditForm(forms.ModelForm):
    class Meta:
        model=Bookings
        fields=('room_name','booking_date','booking_time','end_time')
        widgets = {
            'booking_date': forms.DateInput(attrs={'type': 'date'}),            
            'booking_time': forms.TimeInput(attrs={'type': 'time'}),
            'end_time': forms.TimeInput(attrs={'type': 'time'}),
        }
        
class ParticipantForm(forms.Form):
    participants=forms.ModelChoiceField(queryset=Login.objects.all())
    

clovia/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse
# Create your views here.
from .forms import LoginForm,BookingForm,EditForm,ParticipantForm
from django.views import generic
from .models import Login,Meeting_Rooms, Bookings, Notification
from datetime import datetime,timezone,timedelta
from django.db.models import Q
from asgiref.sync import async_to_sync
from django.core.mail import send_mail
from .google_calendar import create_event,event_removal,event_addition,update_event

@async_to_sync
async def send_email_notification(subject, message, from_email, recipient_list):
    send_mail(subject, message, from_email, recipient_list)

def extract_name_from_username(username):
    #extract the name part
    local_part=username.split('@')[0]
    #extract first name
    first_name= local_part.split(".")[0]
    first_name = first_name.capitalize()
    return f"{first_name}"

#login page view
def home(request):
    context = {}
    form = LoginForm()

    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            temp = form.cleaned_data.get("username")
            login=form.save() 
            return redirect("clovia:meeting_rooms", login_id=login.id)
        else:
            context['form'] = form
            return render(request, "clovia/invalid.html", context)
        
    context['form'] = form
    return render(request, "clovia/home.html", context)

#all meeting rooms
class Meeting_RoomsView(generic.ListView):
    template_name = "clovia/meeting_rooms.html"
    context_object_name = "room_list"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        login_id = self.kwargs.get('login_id')
        
        #we get the username who has logged in
        login = get_object_or_404(Login,pk=login_id)
        #using the function defined above we extract the first name
        name = extract_name_from_username(login.username)      
        context['name'] = name
        context['login']=login
        
        #Delete Past Notifications
        now=datetime.now().date()
        past_bookings=Bookings.objects.filter(booking_date__lt=now)
        for booking in past_bookings:
            past_booking_datetime = datetime.combine(booking.booking_date, booking.booking_time)
            if past_booking_datetime < datetime.now():
                notification_criteria = (Q(message__contains=str(booking.booking_date)) & Q(message__contains=str(booking.booking_time)))
                Notification.objects.filter(notification_criteria).delete()
                 
        # Fetch and mark notifications
        notifications = Notification.objects.filter(receiver=login)
        print("Notifications Queryset:", notifications)
        notifications.update(is_read=True)
        context['notifications'] = notifications
        return context

    def get_queryset(self):
        queryset= Meeting_Rooms.objects.all()
        #get the data from the form 
        date = self.request.GET.get('date')
        time = self.request.GET.get('time')

        if date and time:
            #Convert them into datetime objects and filter the meeting rooms based on the provided date and time
            datetime_str = f"{date} {time}"
            booking_datetime = datetime.strptime(datetime_str, "%Y-%m-%d %H:%M")
            
            # Get the booked meeting rooms
            booked_rooms = Bookings.objects.filter(
                booking_date=booking_datetime.date(),
                booking_time=booking_datetime.time()
            ).values_list('room_name_id', flat=True)

            # Exclude the booked meeting rooms from the queryset
            queryset = queryset.exclude(id__in=booked_rooms)

        return queryset
    
def bookings(request,login_id,rooms_id):
    login = get_object_or_404(Login,pk=login_id)
    room = get_object_or_404(Meeting_Rooms,pk=rooms_id)
    form = BookingForm()
    context = {'login': login,'room': room}
    if request.method == 'POST':
        form = BookingForm(request.POST)
        if form.is_valid():
            #we get the cleaned data
            participant=form.cleaned_data.get("participants")
            b_date = form.cleaned_data.get("booking_date")
            b_time = form.cleaned_data.get("booking_time")
            e_time = form.cleaned_data.get("end_time")
            context['form'] = form
            # Check if the booking date is in the past
            current_datetime = datetime.now()
            booking_datetime = datetime.combine(b_date, b_time)
            end_datetime=datetime.combine(b_date, e_time)
            # Calculate the timezone offset based on the user's timezone
            user_timezone_offset = booking_datetime.astimezone(timezone.utc).strftime('%z')
            # Format start and end times with timezone offset
            start_time_formatted = booking_datetime.strftime('%Y-%m-%dT%H:%M:%S') + user_timezone_offset
            end_time_formatted = end_datetime.strftime('%Y-%m-%dT%H:%M:%S') + user_timezone_offset
    
            if booking_datetime < current_datetime:
                context['message'] = 'Cannot book in the past!'
                return render(request, 'clovia/booking.html', context)

            #check if end time is before starting time
            if e_time<b_time:
                context['message'] = 'End Time in the past!'
                return render(request, 'clovia/booking.html', context)

            #check if the booking already exists
            if Bookings.objects.filter(room_name=room,booking_date=b_date,booking_time__lte=e_time,end_time__gte=b_time).exists():
                context['message'] = 'Booking already exists!'
                return render(request, 'clovia/booking.html',context)

            else:
                booking = Bookings.objects.create(user=login,room_name=room,booking_date=b_date,booking_time=b_time,end_time=e_time)
                #set participants               
                booking.participants.set(participant)
                
                #sending meeting inviation in google calendar
                participants_emails = [participant_user.username for participant_user in participant.all()]
                create_event(f'{room.room}',start_time_formatted,end_time_formatted,participants_emails,booking)
                
                #send notifications and email invitaion
                for participant_user in participant.all():
                    notification_message = f"{login} has added you as a participant to the meeting on {b_date} at {b_time} in {room.room}."
                    Notification.objects.create(receiver=participant_user, message=notification_message)
                    subject = 'Meeting Invitation'
                    message = notification_message
                    from_email = login
                    recipient_list = [participant_user]
                    send_email_notification(subject, message, from_email, recipient_list)
                    
                context['message'] = 'Booking Successful!'
                return render(request, 'clovia/booking.html',context) 
    
    context['form'] = form
    return render(request, "clovia/booking.html", context)

#booked slots
def slots(request,login_id,rooms_id):
    login = Login.objects.get(pk=login_id)
    room = Meeting_Rooms.objects.get(pk=rooms_id)
    #Delete Past Bookings
    now=datetime.now().date()
    past_bookings=Bookings.objects.filter(booking_date__lt=now)
    for booking in past_bookings:
        past_booking_datetime = datetime.combine(booking.booking_date, booking.booking_time)
        if past_booking_datetime < datetime.now():
            Bookings.objects.filter(booking_date=booking.booking_date , booking_time=booking.booking_time).delete()        
    
    query_results = Bookings.objects.filter(room_name=room).order_by("-booking_date")
    return render(request,'clovia/slots.html',{'login': login, 'room': room,'query_results':query_results})

#your meetings
def meetings(request,login_id):
    login = Login.objects.get(pk=login_id)  

    #Delete Past Meetings
    now=datetime.now().date()
    past_bookings=Bookings.objects.filter(booking_date__lt=now)
    for booking in past_bookings:
        past_booking_datetime = datetime.combine(booking.booking_date, booking.booking_time)
        if past_booking_datetime < datetime.now():
            booking.delete()        
    
    user_meetings = Bookings.objects.filter(user=login)
    participant_meetings = Bookings.objects.filter(participants=login)
    all_meetings = user_meetings.union(participant_meetings).order_by("-booking_date")
    return render(request,'clovia/meetings.html',{'login': login,'query_results':all_meetings})

#your bookings
def view_bookings(request,login_id):
    login = Login.objects.get(pk=login_id)
    query_results = Bookings.objects.filter(user=login).order_by("-booking_date")
    return render(request,'clovia/view_bookings.html',{'login': login,'query_results':query_results})

#edit bookings
def edit_booking(request, booking_id,login_id):
    booking = get_object_or_404(Bookings, id=booking_id)
    login = Login.objects.get(pk=login_id)
    context = {'login': login,'booking':booking}
    if request.method == 'POST':
        form = EditForm(request.POST, instance=booking)
        if form.is_valid():
            room=form.cleaned_data.get("room_name")
            b_date = form.cleaned_data.get("booking_date")
            b_time = form.cleaned_data.get("booking_time")
            e_time = form.cleaned_data.get("end_time")
            context['form'] = form
            # Check if the booking date is in the past
            current_datetime = datetime.now()
            booking_datetime = datetime.combine(b_date, b_time)
            end_datetime=datetime.combine(b_date, e_time)
            user_timezone_offset = booking_datetime.astimezone(timezone.utc).strftime('%z')

clovia/templates/clovia/add_participant.html
<form method="post">
  {% csrf_token %}
  <label for="participant_email">Participant Email:</label>
  <input type="email" name="participant_email" required>
  <input type="submit" value="Add Participant">
</form>

clovia/templates/clovia/booking.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
      <link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">

	{% load static %}

<link rel="stylesheet" href="{% static 'clovia/booking.css' %}">

</head>
<body>
  <div id="head"><header>Clovia</header>
</div>
<!-- add nav bar and a h3 heading "Enter Your Booking Details"-->
<div id="nav"><ul>
	    <li><a href="	{% url 'clovia:meeting_rooms' login.id %}">Home</a></li>
      <li><a href="{% url 'clovia:slots' login_id=login.id rooms_id=room.id %}">Booked Slots</a></li>
      <li><a class="active" href="">Book This Room</a></li>
      </ul>
    </div>
<div id="box">
	<h3>Enter Booking Details</h3>
  <div id="booking">
	  <form action="" method="post">
	    {% csrf_token %}
	    {{ form }}
	    <input type="submit" value="Book">
	  </form>
  </div>

        {% if message %}
            <p style="text-align: center; color: red;">{{ message }}</p>
        {% endif %}
</div>
</body>
</html>

clovia/templates/clovia/edit_booking.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title></title>
  <link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">

  {% load static %}

<link rel="stylesheet" href="{% static 'clovia/edit_bookings.css' %}">

</head>
<body>
    <div id="head"><header>Clovia</header>
</div>

  <div id="box">

<form method="post">
  {% csrf_token %}
      {{ form }}
  <input type="submit" value="Save Changes">
</form>
</div>
        {% if message %}
            <p style="text-align: center; color: red;">{{ message }}</p>
        {% endif %}

</body>
</html>

clovia/templates/clovia/home.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title></title>
      <link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">

	{% load static %}

<link rel="stylesheet" href="{% static 'clovia/home.css' %}">

</head>
<body>
  <div id="head"><header>Clovia</header>
</div>

<div id="login">
<form action="" method="post"><h3>Login Form</h3>
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Login">
</form>
</div>
</body>
</html>

clovia/templates/clovia/invalid.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
      <link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">

	{% load static %}

<link rel="stylesheet" href="{% static 'clovia/invalid.css' %}">

</head>
<body>
  <div id="head"><header>Clovia</header>
</div>

<div id="login">
<form action="" method="post"><h3>Login Form</h3>
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Register">
</form>
</div>
<!-- Display validation error messages 
{% if form.errors %}
  <ul>
    {% for field in form %}
      {% for error in field.errors %}
        <li>{{ error }}</li>
      {% endfor %}
    {% endfor %}
  </ul>
{% endif %}
-->
</body>
</html>

clovia/templates/clovia/invitation_email.html
<!-- invitation_email.html -->
<<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
<p>Hello {{ user.username }},</p>
<p>You are invited to a meeting:</p>
<p>Date: {{ meeting.date }}</p>
<p>Location: {{ meeting.location }}</p>
<p>Agenda: {{ meeting.agenda }}</p>
<p>...</p>
<p>Please RSVP at your earliest convenience.</p>
<p>Best regards,</p>
<p>Your Team</p>

</body>
</html>

clovia/templates/clovia/meeting_rooms.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" href="{% static 'clovia/meeting_rooms.css' %}">
</head>
<body>
    <div id="head"><header>Clovia</header>
</div>

<div id="nav"><ul>
      <li><a class="active" href="">Meeting Rooms</a></li>
      <li><a href="{% url 'clovia:meetings' login_id=login.id%}">Your Meetings</a></li>
      <li><a href="{% url 'clovia:view_bookings' login_id=login.id%}">Your Bookings</a></li>
      <li><div class="dropdown">
        <button class="dropbtn">Notifications <i class="fa fa-caret-down"></i></button>
        <div class="dropdown-content"><ul>
        {% if notifications %}
            {% for notification in notifications %}
                <li>{{ notification.message }}</li>
            {% endfor %}
        {% else %}
            <li>No Notifications</li>
        {% endif %}
        </ul>
        </div></div></li>
      </ul>
    </div>
<h1>Welcome {{name}}</h1>
    <form method="GET" action="" >
        {% csrf_token %}
        <div id="inputs"style="position:absolute;right:2%;">
            <input type="date" name="date" required style="border-radius: 10px;margin-right:12px;">
            <input type="time" name="time" style="border-radius: 15px;">
        </div>
        <button type="submit"style="position:absolute;right:3%; top:43.3%;border-radius: 20px;background-color:black; color: white;padding:5px 8px;">Search Available Rooms</button>
    </form>

<div id="list">
    {% if room_list %}
    <ul>
    {% for rooms in room_list %}
        <li><a href="{% url 'clovia:bookings' login.id rooms.id %}">{{ rooms.room }}</a></li>
        <svg width="800" height="180">
            <a href="{% url 'clovia:bookings' login.id rooms.id %}">
            <rect x="70" y="20" rx="20" ry="20" width="650" height="150"/></a>
        </svg>

    {% endfor %}
    </ul>
</div>
{% else %}
    <p>No rooms are available.</p>
{% endif %}
</body>
</html>

clovia/templates/clovia/meetings.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Booked Slots</title>
    <link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">

	{% load static %}

<link rel="stylesheet" href="{% static 'clovia/slots.css' %}">

</head>
<body>
    <div id="head">
        <header>Clovia</header>
    </div>
    <div id="nav"><ul>
      <li><a href="	{% url 'clovia:meeting_rooms' login.id %}">Meeting Rooms</a></li>
      <li><a class="active" href="">Your Meetings</a></li>
      <li><a href="{% url 'clovia:view_bookings' login_id=login.id%}">Your Bookings</a></li>

      </ul>
    </div>

        <!--<h3>Booked Slots</h3>-->
        <div id="booking">
            <table>
                <thead>
                    <tr>
                        <th>Host</th>
                        <th>Room Name</th>
                        <th>Meeting Date</th>
                        <th>Starts At</th>
                        <th>Ends At</th>
                    </tr>
                </thead>
                <tbody>
                    {% for booking in query_results %}
                    <tr>
                        <td>{{booking.user.username}}</td>
                        <td>{{ booking.room_name.room }}</td>
                        <td>{{ booking.booking_date }}</td>
                        <td>{{ booking.booking_time }}</td>
                        <td>{{ booking.end_time }}</td>

                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    
</body>
</html>

clovia/templates/clovia/participants.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Booked Slots</title>
    <link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">

	{% load static %}

<link rel="stylesheet" href="{% static 'clovia/slots.css' %}">

</head>
<body>
    <div id="head">
        <header>Clovia</header>
    </div>
        <!--<h3>Participants for room 1</h3>-->
        <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add Participant</button>
    </form>

        <div id="booking">
            <table>
                <thead>
                    <tr>
                        <th>View Participants</th>
                        <th>Remove Participant</th>
                    </tr>
                </thead>
                <tbody>
                    {% for participant in participants %}
                    <tr> 
                        <td>{{ participant.username }}</td>
                        <td>
                           <form method="post">
                            {% csrf_token %}
                               <input type="hidden" name="remove_participant" value="{{ participant.id }}">
                               <button type="submit">Remove</button>
                           </form>
                       </td>

                    </tr>
                    {% endfor %}
                </tbody>
            </table>

        </div>
    
</body>
</html>

clovia/templates/clovia/remove_participant.html
<!--<form method="post">
  {% csrf_token %}
  <p>Are you sure you want to remove {{ participant.username }} from the booking?</p>
  <input type="submit" value="Remove Participant">
</form>-->
<form method="post">
  {% csrf_token %}
  <label for="participant_email">Participant Email:</label>
  <input type="email" name="participant_email" required>
  <input type="submit" value="Remove Participant">
</form>

clovia/templates/clovia/slots.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Booked Slots</title>
    <link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">

	{% load static %}

<link rel="stylesheet" href="{% static 'clovia/slots.css' %}">

</head>
<body>
    <div id="head">
        <header>Clovia</header>
    </div>
    <div id="nav"><ul>
      <li id="n1"><a href="	{% url 'clovia:meeting_rooms' login.id %}">Home</a></li>
      <li id="n2"><a class="active" href="">Booked Slots</a></li>
      <li id="n3"><a href="{% url 'clovia:bookings' login_id=login.id rooms_id=room.id %}">Book This Room</a></li>
      </ul>
    </div>

        <!--<h3>Booked Slots</h3>-->
        <div id="booking">
            <table>
                <thead>
                    <tr>
                        <th>User</th>
                        <th>Booking Date</th>
                        <th>Booking Time</th>
                        <th>Booking Duration</th>
                    </tr>
                </thead>
                <tbody>
                    {% for booking in query_results %}
                    <tr>
                        <td>{{ booking.user.username }}</td>
                        <td>{{ booking.booking_date }}</td>
                        <td>{{ booking.booking_time }}</td>
                        <td>{{ booking.booking_duration }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    
</body>
</html>

clovia/templates/clovia/view_bookings.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Booked Slots</title>
    <link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">

	{% load static %}

<link rel="stylesheet" href="{% static 'clovia/slots.css' %}">

</head>
<body>
    <div id="head">
        <header>Clovia</header>
    </div>
    <div id="nav"><ul>
      <li><a href="	{% url 'clovia:meeting_rooms' login.id %}">Meeting Rooms</a></li>
      <li><a href="{% url 'clovia:meetings' login_id=login.id%}">Your Meetings</a></li>
      <li><a class="active" href="">Your Bookings</a></li>
      </ul>
    </div>

        <!--<h3>Booked Slots</h3>-->
        <div id="booking">
            <table>
                <thead>
                    <tr>
                        <th>Room Name</th>
                        <th>Booking Date</th>
                        <th>Booking Time</th>
                        <th>Ends At</th>
                        <th>Edit Booking</th>
                        <th>View Participants</th>
                    </tr>
                </thead>
                <tbody>
                    {% for booking in query_results %}
                    <tr>
                        <td>{{ booking.room_name.room }}</td>
                        <td>{{ booking.booking_date }}</td>
                        <td>{{ booking.booking_time }}</td>
                        <td>{{booking.end_time}}</td>
                        <td><a href="{% url 'clovia:edit_booking' login.id booking.id  %}">Edit</a></td>
                        <td><a href="{% url 'clovia:view_participants' booking.id  %}">View Participants</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    
</body>
</html>